name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        default: monalisa
        options: 
        - monalisa
        - cschleiden
      fav_animal:
        type: choice
        description: what's your favourite animal
        required: true
        default: snorlax
        options: 
        - pikachu
        - snorlax
        - dragonite
      message:
        description: Enter message
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        description: Enter environment
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"