name: Greet

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
          - adarshjhaa100
          - monalisa1
          - cschleiden2
          - adarshjhaa100323
          - monalisa432432432
          - cschleiden32432432
          - adarshjhaa100234324324
          - monalisa23432432
          - cschleiden4356465465
          - adarshjhaa100657657657
      name_2:
        type: choice
        description: Who to greetss
        options:
          - cat
          - dawg
          - aj
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
