name: Greet

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
          - monalisa
          - cschleiden
          - adarshjhaa100
      name_2:
        type: choice
        description: Who to greetss
        options:
          - cat
          - dawg
          - aj
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
