name: Greet1

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
        

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
